/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat.h"

char **
chat_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Client said: %s\n", *argp);

	char* mssg;
	printf("Your mssg: ");

	size_t len = 0;
	ssize_t linesize = 0;

	linesize = getline(&mssg, &len, stdin);

	mssg[linesize - 1] = '\0';

	result = mssg;

	return &result;
}
