/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FAC_H_RPCGEN
#define _FAC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FAC_PROG 0x23451111
#define FAC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define fac 1
extern  int * fac_1(int *, CLIENT *);
extern  int * fac_1_svc(int *, struct svc_req *);
extern int fac_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fac 1
extern  int * fac_1();
extern  int * fac_1_svc();
extern int fac_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FAC_H_RPCGEN */
