/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GIVETIME_H_RPCGEN
#define _GIVETIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define GIVETIME_PROG 0x23451111
#define GIVETIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define givetime 1
extern  char ** givetime_1(void *, CLIENT *);
extern  char ** givetime_1_svc(void *, struct svc_req *);
extern int givetime_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define givetime 1
extern  char ** givetime_1();
extern  char ** givetime_1_svc();
extern int givetime_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GIVETIME_H_RPCGEN */
