/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <time.h>
#include "givetime.h"

char **
givetime_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Client asked for date and time!\n");

	

	time_t t;
	char buff[500];
	time(&t);
	snprintf(buff,500,"%s",ctime(&t));
	result=buff;

	return &result;
}
